namespace AgroServicios.Vista.Cuentas
{
    partial class CreateUser
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CreateUser));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.maskedDui = new System.Windows.Forms.MaskedTextBox();
            this.DropRole = new Bunifu.UI.WinForms.BunifuDropdown();
            this.txtNewDireccion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnCrearUsuario = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtNewCorreo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNewPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.PickerBirth = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.txtNewFirstName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNewPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNewUser = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SuspendLayout();
            // 
            // maskedDui
            // 
            this.maskedDui.Location = new System.Drawing.Point(435, 292);
            this.maskedDui.Mask = "00000000-0";
            this.maskedDui.Name = "maskedDui";
            this.maskedDui.Size = new System.Drawing.Size(92, 22);
            this.maskedDui.TabIndex = 9;
            // 
            // DropRole
            // 
            this.DropRole.BackColor = System.Drawing.Color.Transparent;
            this.DropRole.BackgroundColor = System.Drawing.Color.White;
            this.DropRole.BorderColor = System.Drawing.Color.Silver;
            this.DropRole.BorderRadius = 1;
            this.DropRole.Color = System.Drawing.Color.Silver;
            this.DropRole.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.DropRole.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.DropRole.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DropRole.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.DropRole.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.DropRole.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.DropRole.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.DropRole.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.DropRole.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.DropRole.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.DropRole.FillDropDown = true;
            this.DropRole.FillIndicator = false;
            this.DropRole.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.DropRole.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.DropRole.ForeColor = System.Drawing.Color.Black;
            this.DropRole.FormattingEnabled = true;
            this.DropRole.Icon = null;
            this.DropRole.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.DropRole.IndicatorColor = System.Drawing.Color.DarkGray;
            this.DropRole.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.DropRole.IndicatorThickness = 2;
            this.DropRole.IsDropdownOpened = false;
            this.DropRole.ItemBackColor = System.Drawing.Color.White;
            this.DropRole.ItemBorderColor = System.Drawing.Color.White;
            this.DropRole.ItemForeColor = System.Drawing.Color.Black;
            this.DropRole.ItemHeight = 26;
            this.DropRole.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.DropRole.ItemHighLightForeColor = System.Drawing.Color.White;
            this.DropRole.ItemTopMargin = 3;
            this.DropRole.Location = new System.Drawing.Point(558, 287);
            this.DropRole.Name = "DropRole";
            this.DropRole.Size = new System.Drawing.Size(239, 32);
            this.DropRole.TabIndex = 10;
            this.DropRole.Text = null;
            this.DropRole.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.DropRole.TextLeftMargin = 5;
            // 
            // txtNewDireccion
            // 
            this.txtNewDireccion.AcceptsReturn = false;
            this.txtNewDireccion.AcceptsTab = false;
            this.txtNewDireccion.AnimationSpeed = 200;
            this.txtNewDireccion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNewDireccion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNewDireccion.AutoSizeHeight = true;
            this.txtNewDireccion.BackColor = System.Drawing.Color.Transparent;
            this.txtNewDireccion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNewDireccion.BackgroundImage")));
            this.txtNewDireccion.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNewDireccion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNewDireccion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNewDireccion.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNewDireccion.BorderRadius = 30;
            this.txtNewDireccion.BorderThickness = 1;
            this.txtNewDireccion.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNewDireccion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNewDireccion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewDireccion.DefaultFont = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNewDireccion.DefaultText = "";
            this.txtNewDireccion.FillColor = System.Drawing.Color.White;
            this.txtNewDireccion.HideSelection = true;
            this.txtNewDireccion.IconLeft = null;
            this.txtNewDireccion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewDireccion.IconPadding = 10;
            this.txtNewDireccion.IconRight = null;
            this.txtNewDireccion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewDireccion.Lines = new string[0];
            this.txtNewDireccion.Location = new System.Drawing.Point(176, 477);
            this.txtNewDireccion.MaxLength = 32767;
            this.txtNewDireccion.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNewDireccion.Modified = false;
            this.txtNewDireccion.Multiline = false;
            this.txtNewDireccion.Name = "txtNewDireccion";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewDireccion.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNewDireccion.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewDireccion.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewDireccion.OnIdleState = stateProperties28;
            this.txtNewDireccion.Padding = new System.Windows.Forms.Padding(3);
            this.txtNewDireccion.PasswordChar = '\0';
            this.txtNewDireccion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNewDireccion.PlaceholderText = "Dirección";
            this.txtNewDireccion.ReadOnly = false;
            this.txtNewDireccion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNewDireccion.SelectedText = "";
            this.txtNewDireccion.SelectionLength = 0;
            this.txtNewDireccion.SelectionStart = 0;
            this.txtNewDireccion.ShortcutsEnabled = true;
            this.txtNewDireccion.Size = new System.Drawing.Size(621, 50);
            this.txtNewDireccion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNewDireccion.TabIndex = 12;
            this.txtNewDireccion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNewDireccion.TextMarginBottom = 0;
            this.txtNewDireccion.TextMarginLeft = 3;
            this.txtNewDireccion.TextMarginTop = 1;
            this.txtNewDireccion.TextPlaceholder = "Dirección";
            this.txtNewDireccion.UseSystemPasswordChar = false;
            this.txtNewDireccion.WordWrap = true;
            // 
            // btnCrearUsuario
            // 
            this.btnCrearUsuario.AllowAnimations = true;
            this.btnCrearUsuario.AllowMouseEffects = true;
            this.btnCrearUsuario.AllowToggling = false;
            this.btnCrearUsuario.AnimationSpeed = 200;
            this.btnCrearUsuario.AutoGenerateColors = false;
            this.btnCrearUsuario.AutoRoundBorders = true;
            this.btnCrearUsuario.AutoSizeLeftIcon = true;
            this.btnCrearUsuario.AutoSizeRightIcon = true;
            this.btnCrearUsuario.BackColor = System.Drawing.Color.Transparent;
            this.btnCrearUsuario.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnCrearUsuario.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCrearUsuario.BackgroundImage")));
            this.btnCrearUsuario.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCrearUsuario.ButtonText = "Crear Usuario";
            this.btnCrearUsuario.ButtonTextMarginLeft = 0;
            this.btnCrearUsuario.ColorContrastOnClick = 45;
            this.btnCrearUsuario.ColorContrastOnHover = 45;
            this.btnCrearUsuario.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnCrearUsuario.CustomizableEdges = borderEdges2;
            this.btnCrearUsuario.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCrearUsuario.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCrearUsuario.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnCrearUsuario.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCrearUsuario.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCrearUsuario.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCrearUsuario.ForeColor = System.Drawing.Color.White;
            this.btnCrearUsuario.IconLeft = null;
            this.btnCrearUsuario.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCrearUsuario.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCrearUsuario.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCrearUsuario.IconMarginLeft = 11;
            this.btnCrearUsuario.IconPadding = 10;
            this.btnCrearUsuario.IconRight = null;
            this.btnCrearUsuario.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCrearUsuario.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCrearUsuario.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCrearUsuario.IconSize = 25;
            this.btnCrearUsuario.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCrearUsuario.IdleBorderRadius = 0;
            this.btnCrearUsuario.IdleBorderThickness = 0;
            this.btnCrearUsuario.IdleFillColor = System.Drawing.Color.Empty;
            this.btnCrearUsuario.IdleIconLeftImage = null;
            this.btnCrearUsuario.IdleIconRightImage = null;
            this.btnCrearUsuario.IndicateFocus = false;
            this.btnCrearUsuario.Location = new System.Drawing.Point(381, 575);
            this.btnCrearUsuario.Name = "btnCrearUsuario";
            this.btnCrearUsuario.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCrearUsuario.OnDisabledState.BorderRadius = 51;
            this.btnCrearUsuario.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCrearUsuario.OnDisabledState.BorderThickness = 1;
            this.btnCrearUsuario.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCrearUsuario.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCrearUsuario.OnDisabledState.IconLeftImage = null;
            this.btnCrearUsuario.OnDisabledState.IconRightImage = null;
            this.btnCrearUsuario.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCrearUsuario.onHoverState.BorderRadius = 51;
            this.btnCrearUsuario.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCrearUsuario.onHoverState.BorderThickness = 1;
            this.btnCrearUsuario.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCrearUsuario.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCrearUsuario.onHoverState.IconLeftImage = null;
            this.btnCrearUsuario.onHoverState.IconRightImage = null;
            this.btnCrearUsuario.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCrearUsuario.OnIdleState.BorderRadius = 51;
            this.btnCrearUsuario.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCrearUsuario.OnIdleState.BorderThickness = 1;
            this.btnCrearUsuario.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCrearUsuario.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCrearUsuario.OnIdleState.IconLeftImage = null;
            this.btnCrearUsuario.OnIdleState.IconRightImage = null;
            this.btnCrearUsuario.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCrearUsuario.OnPressedState.BorderRadius = 51;
            this.btnCrearUsuario.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCrearUsuario.OnPressedState.BorderThickness = 1;
            this.btnCrearUsuario.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCrearUsuario.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCrearUsuario.OnPressedState.IconLeftImage = null;
            this.btnCrearUsuario.OnPressedState.IconRightImage = null;
            this.btnCrearUsuario.Size = new System.Drawing.Size(186, 51);
            this.btnCrearUsuario.TabIndex = 11;
            this.btnCrearUsuario.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCrearUsuario.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCrearUsuario.TextMarginLeft = 0;
            this.btnCrearUsuario.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCrearUsuario.UseDefaultRadiusAndThickness = true;
            // 
            // txtNewCorreo
            // 
            this.txtNewCorreo.AcceptsReturn = false;
            this.txtNewCorreo.AcceptsTab = false;
            this.txtNewCorreo.AnimationSpeed = 200;
            this.txtNewCorreo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNewCorreo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNewCorreo.AutoSizeHeight = true;
            this.txtNewCorreo.BackColor = System.Drawing.Color.Transparent;
            this.txtNewCorreo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNewCorreo.BackgroundImage")));
            this.txtNewCorreo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNewCorreo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNewCorreo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNewCorreo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNewCorreo.BorderRadius = 30;
            this.txtNewCorreo.BorderThickness = 1;
            this.txtNewCorreo.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNewCorreo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNewCorreo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewCorreo.DefaultFont = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNewCorreo.DefaultText = "";
            this.txtNewCorreo.FillColor = System.Drawing.Color.White;
            this.txtNewCorreo.HideSelection = true;
            this.txtNewCorreo.IconLeft = null;
            this.txtNewCorreo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewCorreo.IconPadding = 10;
            this.txtNewCorreo.IconRight = null;
            this.txtNewCorreo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewCorreo.Lines = new string[0];
            this.txtNewCorreo.Location = new System.Drawing.Point(176, 409);
            this.txtNewCorreo.MaxLength = 32767;
            this.txtNewCorreo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNewCorreo.Modified = false;
            this.txtNewCorreo.Multiline = false;
            this.txtNewCorreo.Name = "txtNewCorreo";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewCorreo.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNewCorreo.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewCorreo.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewCorreo.OnIdleState = stateProperties32;
            this.txtNewCorreo.Padding = new System.Windows.Forms.Padding(3);
            this.txtNewCorreo.PasswordChar = '\0';
            this.txtNewCorreo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNewCorreo.PlaceholderText = "Correo eléctronico";
            this.txtNewCorreo.ReadOnly = false;
            this.txtNewCorreo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNewCorreo.SelectedText = "";
            this.txtNewCorreo.SelectionLength = 0;
            this.txtNewCorreo.SelectionStart = 0;
            this.txtNewCorreo.ShortcutsEnabled = true;
            this.txtNewCorreo.Size = new System.Drawing.Size(621, 50);
            this.txtNewCorreo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNewCorreo.TabIndex = 8;
            this.txtNewCorreo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNewCorreo.TextMarginBottom = 0;
            this.txtNewCorreo.TextMarginLeft = 3;
            this.txtNewCorreo.TextMarginTop = 1;
            this.txtNewCorreo.TextPlaceholder = "Correo eléctronico";
            this.txtNewCorreo.UseSystemPasswordChar = false;
            this.txtNewCorreo.WordWrap = true;
            // 
            // txtNewPhone
            // 
            this.txtNewPhone.AcceptsReturn = false;
            this.txtNewPhone.AcceptsTab = false;
            this.txtNewPhone.AnimationSpeed = 200;
            this.txtNewPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNewPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNewPhone.AutoSizeHeight = true;
            this.txtNewPhone.BackColor = System.Drawing.Color.Transparent;
            this.txtNewPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNewPhone.BackgroundImage")));
            this.txtNewPhone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNewPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNewPhone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNewPhone.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNewPhone.BorderRadius = 30;
            this.txtNewPhone.BorderThickness = 1;
            this.txtNewPhone.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNewPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNewPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPhone.DefaultFont = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNewPhone.DefaultText = "";
            this.txtNewPhone.FillColor = System.Drawing.Color.White;
            this.txtNewPhone.HideSelection = true;
            this.txtNewPhone.IconLeft = null;
            this.txtNewPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPhone.IconPadding = 10;
            this.txtNewPhone.IconRight = null;
            this.txtNewPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPhone.Lines = new string[0];
            this.txtNewPhone.Location = new System.Drawing.Point(176, 343);
            this.txtNewPhone.MaxLength = 32767;
            this.txtNewPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNewPhone.Modified = false;
            this.txtNewPhone.Multiline = false;
            this.txtNewPhone.Name = "txtNewPhone";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPhone.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNewPhone.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPhone.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPhone.OnIdleState = stateProperties36;
            this.txtNewPhone.Padding = new System.Windows.Forms.Padding(3);
            this.txtNewPhone.PasswordChar = '\0';
            this.txtNewPhone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNewPhone.PlaceholderText = "Numero celular";
            this.txtNewPhone.ReadOnly = false;
            this.txtNewPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNewPhone.SelectedText = "";
            this.txtNewPhone.SelectionLength = 0;
            this.txtNewPhone.SelectionStart = 0;
            this.txtNewPhone.ShortcutsEnabled = true;
            this.txtNewPhone.Size = new System.Drawing.Size(621, 50);
            this.txtNewPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNewPhone.TabIndex = 7;
            this.txtNewPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNewPhone.TextMarginBottom = 0;
            this.txtNewPhone.TextMarginLeft = 3;
            this.txtNewPhone.TextMarginTop = 1;
            this.txtNewPhone.TextPlaceholder = "Numero celular";
            this.txtNewPhone.UseSystemPasswordChar = false;
            this.txtNewPhone.WordWrap = true;
            // 
            // PickerBirth
            // 
            this.PickerBirth.BackColor = System.Drawing.Color.Transparent;
            this.PickerBirth.BorderColor = System.Drawing.Color.Silver;
            this.PickerBirth.BorderRadius = 1;
            this.PickerBirth.Color = System.Drawing.Color.Silver;
            this.PickerBirth.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.PickerBirth.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.PickerBirth.DisabledColor = System.Drawing.Color.Gray;
            this.PickerBirth.DisplayWeekNumbers = false;
            this.PickerBirth.DPHeight = 0;
            this.PickerBirth.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.PickerBirth.FillDatePicker = false;
            this.PickerBirth.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.PickerBirth.ForeColor = System.Drawing.Color.Black;
            this.PickerBirth.Icon = ((System.Drawing.Image)(resources.GetObject("PickerBirth.Icon")));
            this.PickerBirth.IconColor = System.Drawing.Color.Gray;
            this.PickerBirth.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.PickerBirth.LeftTextMargin = 5;
            this.PickerBirth.Location = new System.Drawing.Point(176, 287);
            this.PickerBirth.MinimumSize = new System.Drawing.Size(4, 32);
            this.PickerBirth.Name = "PickerBirth";
            this.PickerBirth.Size = new System.Drawing.Size(236, 32);
            this.PickerBirth.TabIndex = 5;
            // 
            // txtNewFirstName
            // 
            this.txtNewFirstName.AcceptsReturn = false;
            this.txtNewFirstName.AcceptsTab = false;
            this.txtNewFirstName.AnimationSpeed = 200;
            this.txtNewFirstName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNewFirstName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNewFirstName.AutoSizeHeight = true;
            this.txtNewFirstName.BackColor = System.Drawing.Color.Transparent;
            this.txtNewFirstName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNewFirstName.BackgroundImage")));
            this.txtNewFirstName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNewFirstName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNewFirstName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNewFirstName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNewFirstName.BorderRadius = 30;
            this.txtNewFirstName.BorderThickness = 1;
            this.txtNewFirstName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNewFirstName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNewFirstName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewFirstName.DefaultFont = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNewFirstName.DefaultText = "";
            this.txtNewFirstName.FillColor = System.Drawing.Color.White;
            this.txtNewFirstName.HideSelection = true;
            this.txtNewFirstName.IconLeft = null;
            this.txtNewFirstName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewFirstName.IconPadding = 10;
            this.txtNewFirstName.IconRight = null;
            this.txtNewFirstName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewFirstName.Lines = new string[0];
            this.txtNewFirstName.Location = new System.Drawing.Point(176, 212);
            this.txtNewFirstName.MaxLength = 32767;
            this.txtNewFirstName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNewFirstName.Modified = false;
            this.txtNewFirstName.Multiline = false;
            this.txtNewFirstName.Name = "txtNewFirstName";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewFirstName.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNewFirstName.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewFirstName.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewFirstName.OnIdleState = stateProperties40;
            this.txtNewFirstName.Padding = new System.Windows.Forms.Padding(3);
            this.txtNewFirstName.PasswordChar = '\0';
            this.txtNewFirstName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNewFirstName.PlaceholderText = "Nombre completo";
            this.txtNewFirstName.ReadOnly = false;
            this.txtNewFirstName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNewFirstName.SelectedText = "";
            this.txtNewFirstName.SelectionLength = 0;
            this.txtNewFirstName.SelectionStart = 0;
            this.txtNewFirstName.ShortcutsEnabled = true;
            this.txtNewFirstName.Size = new System.Drawing.Size(621, 50);
            this.txtNewFirstName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNewFirstName.TabIndex = 3;
            this.txtNewFirstName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNewFirstName.TextMarginBottom = 0;
            this.txtNewFirstName.TextMarginLeft = 3;
            this.txtNewFirstName.TextMarginTop = 1;
            this.txtNewFirstName.TextPlaceholder = "Nombre completo";
            this.txtNewFirstName.UseSystemPasswordChar = false;
            this.txtNewFirstName.WordWrap = true;
            // 
            // txtNewPassword
            // 
            this.txtNewPassword.AcceptsReturn = false;
            this.txtNewPassword.AcceptsTab = false;
            this.txtNewPassword.AnimationSpeed = 200;
            this.txtNewPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNewPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNewPassword.AutoSizeHeight = true;
            this.txtNewPassword.BackColor = System.Drawing.Color.Transparent;
            this.txtNewPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNewPassword.BackgroundImage")));
            this.txtNewPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNewPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNewPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNewPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNewPassword.BorderRadius = 30;
            this.txtNewPassword.BorderThickness = 1;
            this.txtNewPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNewPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNewPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNewPassword.DefaultText = "";
            this.txtNewPassword.FillColor = System.Drawing.Color.White;
            this.txtNewPassword.HideSelection = true;
            this.txtNewPassword.IconLeft = null;
            this.txtNewPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPassword.IconPadding = 10;
            this.txtNewPassword.IconRight = null;
            this.txtNewPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPassword.Lines = new string[0];
            this.txtNewPassword.Location = new System.Drawing.Point(176, 138);
            this.txtNewPassword.MaxLength = 32767;
            this.txtNewPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNewPassword.Modified = false;
            this.txtNewPassword.Multiline = false;
            this.txtNewPassword.Name = "txtNewPassword";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPassword.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNewPassword.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPassword.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPassword.OnIdleState = stateProperties44;
            this.txtNewPassword.Padding = new System.Windows.Forms.Padding(3);
            this.txtNewPassword.PasswordChar = '\0';
            this.txtNewPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNewPassword.PlaceholderText = "Contraseña";
            this.txtNewPassword.ReadOnly = false;
            this.txtNewPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNewPassword.SelectedText = "";
            this.txtNewPassword.SelectionLength = 0;
            this.txtNewPassword.SelectionStart = 0;
            this.txtNewPassword.ShortcutsEnabled = true;
            this.txtNewPassword.Size = new System.Drawing.Size(621, 50);
            this.txtNewPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNewPassword.TabIndex = 2;
            this.txtNewPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNewPassword.TextMarginBottom = 0;
            this.txtNewPassword.TextMarginLeft = 3;
            this.txtNewPassword.TextMarginTop = 1;
            this.txtNewPassword.TextPlaceholder = "Contraseña";
            this.txtNewPassword.UseSystemPasswordChar = false;
            this.txtNewPassword.WordWrap = true;
            // 
            // txtNewUser
            // 
            this.txtNewUser.AcceptsReturn = false;
            this.txtNewUser.AcceptsTab = false;
            this.txtNewUser.AnimationSpeed = 200;
            this.txtNewUser.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNewUser.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNewUser.AutoSizeHeight = true;
            this.txtNewUser.BackColor = System.Drawing.Color.Transparent;
            this.txtNewUser.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNewUser.BackgroundImage")));
            this.txtNewUser.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNewUser.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNewUser.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNewUser.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNewUser.BorderRadius = 30;
            this.txtNewUser.BorderThickness = 1;
            this.txtNewUser.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNewUser.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNewUser.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewUser.DefaultFont = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNewUser.DefaultText = "";
            this.txtNewUser.FillColor = System.Drawing.Color.White;
            this.txtNewUser.HideSelection = true;
            this.txtNewUser.IconLeft = null;
            this.txtNewUser.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewUser.IconPadding = 10;
            this.txtNewUser.IconRight = null;
            this.txtNewUser.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewUser.Lines = new string[0];
            this.txtNewUser.Location = new System.Drawing.Point(176, 69);
            this.txtNewUser.MaxLength = 32767;
            this.txtNewUser.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNewUser.Modified = false;
            this.txtNewUser.Multiline = false;
            this.txtNewUser.Name = "txtNewUser";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewUser.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNewUser.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewUser.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewUser.OnIdleState = stateProperties48;
            this.txtNewUser.Padding = new System.Windows.Forms.Padding(3);
            this.txtNewUser.PasswordChar = '\0';
            this.txtNewUser.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNewUser.PlaceholderText = "Usuario";
            this.txtNewUser.ReadOnly = false;
            this.txtNewUser.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNewUser.SelectedText = "";
            this.txtNewUser.SelectionLength = 0;
            this.txtNewUser.SelectionStart = 0;
            this.txtNewUser.ShortcutsEnabled = true;
            this.txtNewUser.Size = new System.Drawing.Size(621, 50);
            this.txtNewUser.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNewUser.TabIndex = 1;
            this.txtNewUser.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNewUser.TextMarginBottom = 0;
            this.txtNewUser.TextMarginLeft = 3;
            this.txtNewUser.TextMarginTop = 1;
            this.txtNewUser.TextPlaceholder = "Usuario";
            this.txtNewUser.UseSystemPasswordChar = false;
            this.txtNewUser.WordWrap = true;
            // 
            // CreateUser
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.LightSkyBlue;
            this.ClientSize = new System.Drawing.Size(954, 638);
            this.Controls.Add(this.txtNewDireccion);
            this.Controls.Add(this.btnCrearUsuario);
            this.Controls.Add(this.DropRole);
            this.Controls.Add(this.maskedDui);
            this.Controls.Add(this.txtNewCorreo);
            this.Controls.Add(this.txtNewPhone);
            this.Controls.Add(this.PickerBirth);
            this.Controls.Add(this.txtNewFirstName);
            this.Controls.Add(this.txtNewPassword);
            this.Controls.Add(this.txtNewUser);
            this.MaximumSize = new System.Drawing.Size(972, 685);
            this.MinimumSize = new System.Drawing.Size(972, 685);
            this.Name = "CreateUser";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "CreateUser";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        public Bunifu.UI.WinForms.BunifuTextBox txtNewUser;
        public Bunifu.UI.WinForms.BunifuTextBox txtNewPassword;
        public Bunifu.UI.WinForms.BunifuTextBox txtNewFirstName;
        public Bunifu.UI.WinForms.BunifuTextBox txtNewPhone;
        public Bunifu.UI.WinForms.BunifuTextBox txtNewCorreo;
        public Bunifu.UI.WinForms.BunifuDatePicker PickerBirth;
        public System.Windows.Forms.MaskedTextBox maskedDui;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCrearUsuario;
        public Bunifu.UI.WinForms.BunifuTextBox txtNewDireccion;
        public Bunifu.UI.WinForms.BunifuDropdown DropRole;
    }
}