//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroServicios {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ingles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ingles() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgroServicios.Ingles", typeof(Ingles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        internal static string Actualizar {
            get {
                return ResourceManager.GetString("Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add image.
        /// </summary>
        internal static string AgregarImagen {
            get {
                return ResourceManager.GetString("AgregarImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add brand.
        /// </summary>
        internal static string AgregarMarca {
            get {
                return ResourceManager.GetString("AgregarMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add product.
        /// </summary>
        internal static string AgregarProducto {
            get {
                return ResourceManager.GetString("AgregarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add to cart.
        /// </summary>
        internal static string AnadirCarrito {
            get {
                return ResourceManager.GetString("AnadirCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database.
        /// </summary>
        internal static string BaseDatos {
            get {
                return ResourceManager.GetString("BaseDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Clients.
        /// </summary>
        internal static string bc {
            get {
                return ResourceManager.GetString("bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        internal static string bienvenida {
            get {
                return ResourceManager.GetString("bienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string BotonInicio {
            get {
                return ResourceManager.GetString("BotonInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        internal static string btnactempleado {
            get {
                return ResourceManager.GetString("btnactempleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add employee.
        /// </summary>
        internal static string btnañadir {
            get {
                return ResourceManager.GetString("btnañadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string btnAñadirP {
            get {
                return ResourceManager.GetString("btnAñadirP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Supplier.
        /// </summary>
        internal static string btnAP {
            get {
                return ResourceManager.GetString("btnAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create user.
        /// </summary>
        internal static string btningresarempleado {
            get {
                return ResourceManager.GetString("btningresarempleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Suplier.
        /// </summary>
        internal static string btnUP {
            get {
                return ResourceManager.GetString("btnUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search product.
        /// </summary>
        internal static string Busqueda {
            get {
                return ResourceManager.GetString("Busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount.
        /// </summary>
        internal static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product quantity.
        /// </summary>
        internal static string CantidadProducto {
            get {
                return ResourceManager.GetString("CantidadProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Characteristics.
        /// </summary>
        internal static string Caracteristicas {
            get {
                return ResourceManager.GetString("Caracteristicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cart.
        /// </summary>
        internal static string Carri {
            get {
                return ResourceManager.GetString("Carri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cell phone number.
        /// </summary>
        internal static string Celular {
            get {
                return ResourceManager.GetString("Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string CMSELIMINAR {
            get {
                return ResourceManager.GetString("CMSELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string CMSELIP {
            get {
                return ResourceManager.GetString("CMSELIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Employee information.
        /// </summary>
        internal static string CMSINFO {
            get {
                return ResourceManager.GetString("CMSINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset employee.
        /// </summary>
        internal static string CMSREST {
            get {
                return ResourceManager.GetString("CMSREST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update data.
        /// </summary>
        internal static string CMSUPDT {
            get {
                return ResourceManager.GetString("CMSUPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        internal static string CMSUPP {
            get {
                return ResourceManager.GetString("CMSUPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product code.
        /// </summary>
        internal static string CodigoProducto {
            get {
                return ResourceManager.GetString("CodigoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buy.
        /// </summary>
        internal static string Comp {
            get {
                return ResourceManager.GetString("Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connecting to the database.
        /// </summary>
        internal static string ConexcionBase {
            get {
                return ResourceManager.GetString("ConexcionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test connection.
        /// </summary>
        internal static string Conexion {
            get {
                return ResourceManager.GetString("Conexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Contrasena {
            get {
                return ResourceManager.GetString("Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string contraseña {
            get {
                return ResourceManager.GetString("contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrator password.
        /// </summary>
        internal static string ContraseñaAdmin {
            get {
                return ResourceManager.GetString("ContraseñaAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password Authentication.
        /// </summary>
        internal static string ContraseñaAuthentication {
            get {
                return ResourceManager.GetString("ContraseñaAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a e-mail.
        /// </summary>
        internal static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create new brand.
        /// </summary>
        internal static string CreateMarca {
            get {
                return ResourceManager.GetString("CreateMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminate.
        /// </summary>
        internal static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Data.
        /// </summary>
        internal static string EditarDatos {
            get {
                return ResourceManager.GetString("EditarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit image.
        /// </summary>
        internal static string EditarImagen {
            get {
                return ResourceManager.GetString("EditarImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Brand.
        /// </summary>
        internal static string EditarMarca {
            get {
                return ResourceManager.GetString("EditarMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Product.
        /// </summary>
        internal static string EditarProducto {
            get {
                return ResourceManager.GetString("EditarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product sheets.
        /// </summary>
        internal static string FichaProducto {
            get {
                return ResourceManager.GetString("FichaProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sales sheets.
        /// </summary>
        internal static string FichaVentas {
            get {
                return ResourceManager.GetString("FichaVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keep.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable SQL Integrated Security.
        /// </summary>
        internal static string HabilitarSql {
            get {
                return ResourceManager.GetString("HabilitarSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable Windows Integrated Security.
        /// </summary>
        internal static string HabilitarWindows {
            get {
                return ResourceManager.GetString("HabilitarWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sales history.
        /// </summary>
        internal static string HistorialVentas {
            get {
                return ResourceManager.GetString("HistorialVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        internal static string Informacion {
            get {
                return ResourceManager.GetString("Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Product.
        /// </summary>
        internal static string IngresarProducto {
            get {
                return ResourceManager.GetString("IngresarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the new password.
        /// </summary>
        internal static string IngreseNuevaContra {
            get {
                return ResourceManager.GetString("IngreseNuevaContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your password.
        /// </summary>
        internal static string IngreseSuContra {
            get {
                return ResourceManager.GetString("IngreseSuContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter your current password.
        /// </summary>
        internal static string IngreseSuContraActual {
            get {
                return ResourceManager.GetString("IngreseSuContraActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your username.
        /// </summary>
        internal static string IngreseSuUsuario {
            get {
                return ResourceManager.GetString("IngreseSuUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Members.
        /// </summary>
        internal static string Integragrantes {
            get {
                return ResourceManager.GetString("Integragrantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Members.
        /// </summary>
        internal static string Integrantes {
            get {
                return ResourceManager.GetString("Integrantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string labelbuscar {
            get {
                return ResourceManager.GetString("labelbuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Login.
        /// </summary>
        internal static string LabeldeInicio {
            get {
                return ResourceManager.GetString("LabeldeInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Employee information.
        /// </summary>
        internal static string LabelFicha {
            get {
                return ResourceManager.GetString("LabelFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset password.
        /// </summary>
        internal static string LabelRestContra {
            get {
                return ResourceManager.GetString("LabelRestContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rest user.
        /// </summary>
        internal static string LabelRestUser {
            get {
                return ResourceManager.GetString("LabelRestUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product table.
        /// </summary>
        internal static string LabelTitulo {
            get {
                return ResourceManager.GetString("LabelTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marc.
        /// </summary>
        internal static string Marca {
            get {
                return ResourceManager.GetString("Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cash Closing.
        /// </summary>
        internal static string mbc {
            get {
                return ResourceManager.GetString("mbc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string mbcf {
            get {
                return ResourceManager.GetString("mbcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Long Out.
        /// </summary>
        internal static string mbe {
            get {
                return ResourceManager.GetString("mbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Sheet .
        /// </summary>
        internal static string mbf {
            get {
                return ResourceManager.GetString("mbf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        internal static string mbp {
            get {
                return ResourceManager.GetString("mbp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weekly Sales Report.
        /// </summary>
        internal static string mbv {
            get {
                return ResourceManager.GetString("mbv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Full name.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brand Name.
        /// </summary>
        internal static string NombreMarca {
            get {
                return ResourceManager.GetString("NombreMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Name.
        /// </summary>
        internal static string NombreProducto {
            get {
                return ResourceManager.GetString("NombreProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        internal static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product price.
        /// </summary>
        internal static string PrecioProducto {
            get {
                return ResourceManager.GetString("PrecioProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesos.
        /// </summary>
        internal static string procesos {
            get {
                return ResourceManager.GetString("procesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suppliers.
        /// </summary>
        internal static string Proveedores {
            get {
                return ResourceManager.GetString("Proveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        internal static string recuperar {
            get {
                return ResourceManager.GetString("recuperar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sales record.
        /// </summary>
        internal static string RegistroVentas {
            get {
                return ResourceManager.GetString("RegistroVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Second answe.
        /// </summary>
        internal static string RespuestaDos {
            get {
                return ResourceManager.GetString("RespuestaDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First answer.
        /// </summary>
        internal static string RespuestaUno {
            get {
                return ResourceManager.GetString("RespuestaUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select.
        /// </summary>
        internal static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server URL.
        /// </summary>
        internal static string ServidorURL {
            get {
                return ResourceManager.GetString("ServidorURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SQL Authentication.
        /// </summary>
        internal static string SqlAuthentication {
            get {
                return ResourceManager.GetString("SqlAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supplies.
        /// </summary>
        internal static string Suministros {
            get {
                return ResourceManager.GetString("Suministros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brand Table.
        /// </summary>
        internal static string TablaMarcas {
            get {
                return ResourceManager.GetString("TablaMarcas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update employee.
        /// </summary>
        internal static string tituloactualizar {
            get {
                return ResourceManager.GetString("tituloactualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter employee.
        /// </summary>
        internal static string tituloingresar {
            get {
                return ResourceManager.GetString("tituloingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Supplier.
        /// </summary>
        internal static string txtAñaP {
            get {
                return ResourceManager.GetString("txtAñaP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail.
        /// </summary>
        internal static string txtCR {
            get {
                return ResourceManager.GetString("txtCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        internal static string txtDUI {
            get {
                return ResourceManager.GetString("txtDUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company.
        /// </summary>
        internal static string txtEM {
            get {
                return ResourceManager.GetString("txtEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Full Name.
        /// </summary>
        internal static string txtFN {
            get {
                return ResourceManager.GetString("txtFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone Number.
        /// </summary>
        internal static string txtTe {
            get {
                return ResourceManager.GetString("txtTe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Supplier.
        /// </summary>
        internal static string txtUp {
            get {
                return ResourceManager.GetString("txtUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrator User.
        /// </summary>
        internal static string UserAdmin {
            get {
                return ResourceManager.GetString("UserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validate data.
        /// </summary>
        internal static string ValidarDatos {
            get {
                return ResourceManager.GetString("ValidarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify.
        /// </summary>
        internal static string Verificar {
            get {
                return ResourceManager.GetString("Verificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Re-enter password.
        /// </summary>
        internal static string VuelvaIngresarContra {
            get {
                return ResourceManager.GetString("VuelvaIngresarContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
